<a href="https://colab.research.google.com/github/mathiastadtlober-max/trabalho_fernando_posser/blob/main/TRABALHO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:

import pandas as pd # importa o pandas e dá um apelido a ele

dados = pd.read_csv("dados.csv") # carregando um csv com o delimitador ;

dados #mostrando na tela

,Carimbo de data/hora,Endereço de e-mail,Você aposta ou já apostou em jogos de azar?,Qual é a sua idade?,Qual seu gênero?,Qual é o seu nível de escolaridade?,"Quantas pessoas, contando com você, moram em sua casa?",Qual classe social você pertence?,O que é um orçamento pessoal?,Qual dessas opções é considerada uma boa prática financeira?,Qual é a principal vantagem de ter uma reserva de emergência?,"O que significa ""gastar menos do que se ganha""?",Quais são suas fontes de renda atualmente?,Porque você começou a apostar?,Você concorda com a afirmação:\nMinhas apostas tem me dado lucro.,"Você concorda com a afirmação:\nQuando fico no prejuízo, continuo apostando.",Com que frequência você aposta?
0,19/06/2025 00:04:14,nikali.hoje@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/06/2025 17:21:56,liztomazelli@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21/06/2025 17:25:04,alanisdiscord12@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21/06/2025 17:36:45,leonardomaziero160@gmail.com,Sim,17 ou 18 anos,Homem cisgênero,Ensino Médio Completo,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,"Mesada dos pais/responsáveis, Outra (especifiq...","Influência de amigos, Curiosidade, Vontade de ...",5.0,4.0,Uma ou duas vezes por semana
4,21/06/2025 17:44:08,ngcdaddy14@gmail.com,Sim,19 ou 20 anos,Homem cisgênero,Ensino Superior Incompleto,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,Mesada dos pais/responsáveis,"Propagandas, Influência de amigos, Curiosidade...",2.0,4.0,DIariamente
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,25/06/2025 16:24:21,bordignonandrieli@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,25/06/2025 16:35:24,davi.mendes@sounotredame.org.br,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,25/06/2025 16:37:31,feijao280986@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,25/06/2025 16:39:17,davimiguelwm@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,25/06/2025 16:46:34,biancavitoriademoura@gmail.com,Sim,19 ou 20 anos,Mulher cisgênero,Pós-graduação (especialização) incompleta,2 pessoas,Renda menor que R$ 3.018.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Acumular dívidas,Trabalho com carteira assinada,Curiosidade,1.0,1.0,Apostei poucas vezes na vida

In [37]:
dados.head() # mostra só as 5 primeiras linhas

,Carimbo de data/hora,Endereço de e-mail,Você aposta ou já apostou em jogos de azar?,Qual é a sua idade?,Qual seu gênero?,Qual é o seu nível de escolaridade?,"Quantas pessoas, contando com você, moram em sua casa?",Qual classe social você pertence?,O que é um orçamento pessoal?,Qual dessas opções é considerada uma boa prática financeira?,Qual é a principal vantagem de ter uma reserva de emergência?,"O que significa ""gastar menos do que se ganha""?",Quais são suas fontes de renda atualmente?,Porque você começou a apostar?,Você concorda com a afirmação:\nMinhas apostas tem me dado lucro.,"Você concorda com a afirmação:\nQuando fico no prejuízo, continuo apostando.",Com que frequência você aposta?
0,19/06/2025 00:04:14,nikali.hoje@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/06/2025 17:21:56,liztomazelli@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21/06/2025 17:25:04,alanisdiscord12@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21/06/2025 17:36:45,leonardomaziero160@gmail.com,Sim,17 ou 18 anos,Homem cisgênero,Ensino Médio Completo,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,"Mesada dos pais/responsáveis, Outra (especifiq...","Influência de amigos, Curiosidade, Vontade de ...",5.0,4.0,Uma ou duas vezes por semana
4,21/06/2025 17:44:08,ngcdaddy14@gmail.com,Sim,19 ou 20 anos,Homem cisgênero,Ensino Superior Incompleto,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,Mesada dos pais/responsáveis,"Propagandas, Influência de amigos, Curiosidade...",2.0,4.0,DIariamente

In [38]:
# mostrar os nomes das colunas
dados.columns

Index(['Carimbo de data/hora', 'Endereço de e-mail',
       'Você aposta ou já apostou em jogos de azar?', 'Qual é a sua idade?',
       'Qual seu gênero?', 'Qual é o seu nível de escolaridade?',
       'Quantas pessoas, contando com você, moram em sua casa?',
       'Qual classe social você pertence?', 'O que é um orçamento pessoal?',
       'Qual dessas opções é considerada uma boa prática financeira?',
       'Qual é a principal vantagem de ter uma reserva de emergência?',
       'O que significa "gastar menos do que se ganha"?',
       '  Quais são suas fontes de renda atualmente?  ',
       'Porque você começou a apostar?',
       'Você concorda com a afirmação:\nMinhas apostas tem me dado lucro.',
       'Você concorda com a afirmação:\nQuando fico no prejuízo, continuo apostando.',
       'Com que frequência você aposta?'],
      dtype='object')

In [64]:
# renomear uma coluna
dados.rename(columns={
    "Qual é o seu nível de escolaridade?": "escolaridade"},
    inplace=True
)
dados.head()

,Carimbo de data/hora,Endereço de e-mail,Você aposta ou já apostou em jogos de azar?,Qual é a sua idade?,Qual seu gênero?,escolaridade,"Quantas pessoas, contando com você, moram em sua casa?",Qual classe social você pertence?,O que é um orçamento pessoal?,Qual dessas opções é considerada uma boa prática financeira?,Qual é a principal vantagem de ter uma reserva de emergência?,"O que significa ""gastar menos do que se ganha""?",Quais são suas fontes de renda atualmente?,Porque você começou a apostar?,Você concorda com a afirmação:\nMinhas apostas tem me dado lucro.,"Você concorda com a afirmação:\nQuando fico no prejuízo, continuo apostando.",Com que frequência você aposta?
0,19/06/2025 00:04:14,nikali.hoje@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21/06/2025 17:21:56,liztomazelli@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,21/06/2025 17:25:04,alanisdiscord12@gmail.com,Não,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,21/06/2025 17:36:45,leonardomaziero160@gmail.com,Sim,17 ou 18 anos,Homem cisgênero,Ensino Médio Completo,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,"Mesada dos pais/responsáveis, Outra (especifiq...","Influência de amigos, Curiosidade, Vontade de ...",5.0,4.0,Uma ou duas vezes por semana
4,21/06/2025 17:44:08,ngcdaddy14@gmail.com,Sim,19 ou 20 anos,Homem cisgênero,Ensino Superior Incompleto,4 pessoas,Acima de R$ 30.180 no mínimo.,Um planejamento das receitas e despesas pessoais,Registrar todas as entradas e saídas de dinheiro,Pagar despesas imprevistas sem se endividar,Ter controle financeiro e possibilidade de poupar,Mesada dos pais/responsáveis,"Propagandas, Influência de amigos, Curiosidade...",2.0,4.0,DIariamente

In [65]:
dados.info() # trás informações gerais sobre cada coluna
# object: string
# int64: inteiro (-10,2,50,1000...)
# float64: ponto flutuante (1.8, 22.345623, -50.30...)
# bool: booleano (True, False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 17 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   Carimbo de data/hora                                                         102 non-null    object
 1   Endereço de e-mail                                                           102 non-null    object
 2   Você aposta ou já apostou em jogos de azar?                                  102 non-null    object
 3   Qual é a sua idade?                                                          52 non-null     object
 4   Qual seu gênero?                                                             51 non-null     object
 5   escolaridade                                                                 51 non-null     object
 6   Quantas pessoas, contando com você, moram em sua casa?                       52 non-null     object
 7   Qual classe social você pertence?                                            52 non-null     object
 8   O que é um orçamento pessoal?                                                52 non-null     object
 9   Qual dessas opções é considerada uma boa prática financeira?                 52 non-null     object
 10  Qual é a principal vantagem de ter uma reserva de emergência?                52 non-null     object
 11  O que significa "gastar menos do que se ganha"?                              52 non-null     object
 12    Quais são suas fontes de renda atualmente?                                 52 non-null     object
 13  Porque você começou a apostar?                                               52 non-null     object
 14  Você concorda com a afirmação:
Minhas apostas tem me dado lucro.             52 non-null     float64
 15  Você concorda com a afirmação:
Quando fico no prejuízo, continuo apostando.  52 non-null     float64
 16  Com que frequência você aposta?                                              52 non-null     object
dtypes: float64(2), object(15)
memory usage: 13.7+ KB

In [68]:
# criar uma coluna booleana

# acessando a coluna "escolaridade"
dados.escolaridade

0                                            NaN
1                                            NaN
2                                            NaN
3                          Ensino Médio Completo
4                     Ensino Superior Incompleto
                         ...
97                                           NaN
98                                           NaN
99                                           NaN
100                                          NaN
101    Pós-graduação (especialização) incompleta
Name: escolaridade, Length: 102, dtype: object

In [72]:
comparacao_escolaridade_frequencia = pd.crosstab(dados['escolaridade'], dados['Com que frequência você aposta?'])
display(comparacao_escolaridade_frequencia)

Com que frequência você aposta?,Apostei poucas vezes na vida,DIariamente,Mensalmente,Uma ou duas vezes por semana
escolaridade,,,,
Ensino Médio Completo,9,2,1,1
Ensino Médio Incompleto,1,0,1,1
Ensino Superior Completo,3,1,2,0
Ensino Superior Incompleto,9,4,5,5
Pós-graduação (especialização) completa,4,0,1,0
Pós-graduação (especialização) incompleta,1,0,0,0